# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ytran <marvin@42.fr>                       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/03/29 21:02:48 by ytran             #+#    #+#              #
#    Updated: 2018/03/29 22:07:34 by ytran            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

SRCS = ft_display_file.c

OUT = ft_diisplay_file.o

all:
	gcc -Wall -Wextra -Werror $(SRCS) -o $(NAME)
clean:
	rm -f $(OUT)

fclean:	clean
	rm -f $(NAME)
